### ISSUE TITLE
Feature request: Support actions monorepos

### ISSUE THREAD

**Issue by fbonander** [actions/publish-immutable-action#222]
I would be great if this action would support monorepo setups. We currently have a monorepo that have a large number  of actions and reusable workflows. 

I'm thinking something like this:

```
 - name: Publish
      id: publish
      uses: actions/publish-immutable-action@0.0.3
      with:
         files-pattern: ./actions/java/unit-tests/**
         name: java/unit-test
```

And then for consumtion:
```
- uses: your-name/mono-repo/java/unit-test@v1
```
